Test for directory existence

diff --git a/scripts/setup_matlab b/scripts/setup_matlab
--- a/scripts/setup_matlab
+++ b/scripts/setup_matlab
@@ -39,6 +39,15 @@ then
 fi
 
 
+###############################################################
+# Make sure the MATLAB base directory exists
+###############################################################
+if [ ! -d "$MATBASE" ];
+then
+	printf "Error: The directory '$MATBASE' does not exist\n"
+	return 1 2> /dev/null || exit 1
+fi
+
 
 ###############################################################
 # Display the help if requested
diff --git a/scripts/setup_xilinx b/scripts/setup_xilinx
--- a/scripts/setup_xilinx
+++ b/scripts/setup_xilinx
@@ -39,6 +39,15 @@ then
 fi
 
 
+###############################################################
+# Make sure the Xilinx base directory exists
+###############################################################
+if [ ! -d "$XILBASE" ];
+then
+    printf "Error: The directory '$XILBASE' does not exist\n"
+    return 1 2> /dev/null || exit 1
+fi
+
 
 ###############################################################
 # Display the help if requested
